# Generated by Django 3.2.6 on 2021-08-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('murandaco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='disc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='murandaco.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
