# Generated by Django 3.2.6 on 2021-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murandaco', '0004_auto_20210830_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='head',
            field=models.CharField(default='always better', max_length=100),
            preserve_default=False,
        ),
    ]
