# Generated by Django 3.2.6 on 2021-09-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('murandaco', '0006_auto_20210902_0520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
